spring:
  application:
    name: ap-ribbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    template:
#      exchange: direct
#    listener:
#      direct:
#        consumers-per-queue: queueDirect
    #设置exchange、queue
#eureka:
#  client:
#    service-url:
#      DefaultZone: http://localhost:8081/eureka
#    fetch-registry: true
#  instance:
#    ip-address: 127.0.0.1
